if __name__ == '__main__':
    with open('test.txt', 'r') as f:
        lines = f.readlines()
    e = 0
    for line in lines:
        line = line[:-3] + '1' + line[-1]
        e += eval(line[line.index('(') + 1:]) == 1
    print(e/len(lines))

    a = '''Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.
Molecule has only 1 atoms.'''
    b = a.split('\n')
    print(len(b))